### ISSUE TITLE
Invalid UInt64 Error

### ISSUE THREAD

**Issue by bradlesh** [Nico-Posada/CoD-LUA-Unhashed#1]
I am getting this error after on all versions, not sure why.

![image](https://github.com/Nico-Posada/CoD-LUA-Unhashed/assets/153047272/242f1209-18b0-416f-83a9-220e023aa954)

**Comment by Nico-Posada** [comment]
Can you send your localize.json file to see what it looks like?

**Comment by bradlesh** [comment]
Never mind! Got it from a buddy who decrypted his localize.json. Would've usually used my own encrypted one, but just reset my PC and forgot to backup my archives so I didn't have everything up and running yet.

You can delete the issue :)

**Comment by Nico-Posada** [comment]
Alright sounds good
